### ISSUE TITLE
Patient's name shows up at the top but does not update and then disappears.

### ISSUE THREAD

**Issue by PhenomX** [CST316GroupC/asthma-game#5]
Example:

ABC logs in.. the top of the Java Swing shows ABC Tutorial.
If user hits "Start" button, now the top says ABC Spirometer Input. (Normal so far)

If user hits "Back" to go back to Tutorial Screen, the top still shows ABC Spirometer Input.
Then if user clicks "Start" to go to Spirometer Input page, it just shows Spirometer Input. No more ABC Spirometer Input.
Then hitting back from Spirometer Input page to go back to Tutorial Page, the top still shows Spirometer Input.

**Comment by jreigel** [comment]
I fixed this, but I noticed that there are no methods about this in the gamehub or the reward screen. Do you guys want it to say "ABC Rewards" and whatnot, or do you just want me to fix it to say "ABC Spirometer Input" no matter how many times they click back?

**Comment by jreigel** [comment]
Also, this might be easier with an enumerated singleton. I could set one up fairly quickly. (2-3 hours tops) I know it was needed for all of my screens in LibGDX, but that is just because libgdx was terrible in that aspect. It really isn't needed here (especially when thinking about the minimum viable product) but it could be helpful for small bugs when switching screens.

**Comment by PhenomX** [comment]
Yes. Go ahead and to that.
